#! /bin/sh -x

mkdir pdiff

DIR1="paper_aimsa_1"
DIR2="paper_aimsa"

cp $DIR2/*.tex pdiff/
cp $DIR2/Makefile pdiff/
cp $DIR2/*sty pdiff/
cp $DIR2/*bib pdiff/
cp $DIR2/*cls pdiff/

for file in `cd $DIR1; ls *tex`; do
    ./texdiff $DIR1/$file $DIR2/$file pdiff/$file;
done


cat pdiff/main.tex | head -n 8 > pdiff/new.tex
cat <<EOF  >> pdiff/new.tex
\usepackage{xcolor} \usepackage{ulem} \usepackage{changebar}
\newcommand\TLSins[1]{\cbstart{}\textcolor{ins}{\uline{#1}}\cbend{}}
\newcommand\TLSdel[1]{\cbdelete{}\textcolor{del}{\sout{#1}}}
\colorlet{ins}{blue} \colorlet{del}{red}
EOF
cat pdiff/main.tex | tail -n +9 >> pdiff/new.tex

mv pdiff/new.tex pdiff/main.tex
