#! /bin/sh

# reboot = +45 sec
# start from button = +41 sec

WAIT=19

for ii in `seq $WAIT -1 1`; do
    echo $ii
    sleep 1
done

# Absolute path to this script. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)
# Absolute path this script is in. /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`

echo $SCRIPT
echo $SCRIPTPATH

FF=`find $SCRIPTPATH/../out/ | grep filt | grep neat_110115_175446_00004_007` && echo $FF &&  $SCRIPTPATH/../justWalk.py $FF
