#! /bin/sh

# Absolute path to this script. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)
# Absolute path this script is in. /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`

echo "got here 2" >> /home/team/log

screen -d -m -S walk
screen -S walk -X zombie qr
screen -S walk -X screen $SCRIPTPATH/delayWalk

echo "got here 3" >> /home/team/log
